---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#
network.host: 0.0.0.0

discovery.type: single-node

bootstrap.memory_lock: true

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.security.enabled: true

xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: 60s

## Add new configuration from here!
#